In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [4]:
array.shape

(3,)

In [5]:
array2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
reshapedArray= array2.reshape(3,5)

In [11]:
print(reshapedArray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
print("shape",reshapedArray.shape)

shape (3, 5)


In [15]:
a = np.array([1,2,3])
b= np.array([4,5,6])
print(a+b)
print(b*a)
print(a-b)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]


In [16]:
newArray=a.copy()
print(newArray)

[1 2 3]


In [17]:
print(array2[0:4])

[1 2 3 4]


In [18]:
print(array2[::-1])

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [19]:
import pandas as pd

In [21]:
dictionary = {"isim":["fatih","hasan","neriman","mustafa","melike"],"yas":[22,60,57,34,27]}

In [22]:
dataframe1 = pd.DataFrame(dictionary)

In [23]:
print(dataframe1)

      isim  yas
0    fatih   22
1    hasan   60
2  neriman   57
3  mustafa   34
4   melike   27


In [24]:
print(dataframe1.columns)

Index(['isim', 'yas'], dtype='object')


In [25]:
dataframe1.columns = [each.upper() for each in dataframe1.columns]
dataframe1.columns

Index(['ISIM', 'YAS'], dtype='object')

In [ ]:
import matplotlib.pyplot as plt
